

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const REGISTER_START = 'REGISTER_START'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED  = 'AUTH_FAILED'

export const FETCH_ONEOFF = 'FETCH_ONEOFF'
export const ONEOFF_LOADING = 'ONEOFF_LOADING'
export const ONEOFF_FAILED  = 'ONEOFF_FAILED'

export const FETCH_SERVICES = 'FETCH_SERVICES'
export const SERVICES_LOADING = 'SERVICES_LOADING'
export const SERVICES_FAILED  = 'SERVICES_FAILED'

export const RESET_PASSWORD = 'RESET_PASSWORD'
export const FORGET_PASSWORD = 'FORGET_PASSWORD'

export const RESET_SUCCESS = 'RESET_SUCCESS'
export const RESET_FAIL = 'RESET_FAIL'

export const REDIRECT = 'REDIRECT'
export const VERIFY_EMAIL = 'VERIFY_EMAIL'





