

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const REGISTER_START = 'REGISTER_START'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED  = 'AUTH_FAILED'

export const FETCH_ONEOFF = 'FETCH_ONEOFF'
export const ONEOFF_LOADING = 'ONEOFF_LOADING'
export const ONEOFF_FAILED  = 'ONEOFF_FAILED'

